language: php

sudo: required

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

jdk:
  - oraclejdk8


before_install:
  - if php -i | grep -q xdebug; then phpenv config-rm xdebug.ini; fi

install:
  - >
    if [[ "$TYPO3" = *"dev"* ]]; then
      composer config minimum-stability dev;
      composer config prefer-stable true;
      composer require typo3/cms-core:"@dev" --no-update;
    fi
  - composer require nimut/typo3-complete:"$TYPO3"
  - export TYPO3_PATH_ROOT=$PWD/.Build/web
  - export typo3DatabaseName=typo3
  - export typo3DatabaseHost=localhost
  - export typo3DatabaseUsername=root
  - export typo3DatabasePassword=

script:
  - >
    if [ -d "Tests/Unit" ]; then
      echo;
      echo "Running unit tests";
      echo;
      echo;
      .Build/bin/phpunit --bootstrap .Build/vendor/nimut/testing-framework/res/Configuration/UnitTestsBootstrap.php Tests/Unit/;
    fi

  - >
    if [ -d "Tests/Functional" ]; then
      echo;
      echo "Running functional tests";
      echo;
      echo;
      find 'Tests/Functional' -wholename '*Test.php' | parallel --gnu 'echo; echo "Running functional test suite {}"; .Build/bin/phpunit --bootstrap .Build/vendor/nimut/testing-framework/res/Configuration/FunctionalTestsBootstrap.php {}';
    fi

  - >
    echo;
    echo "Executing PHP code sniffer";
    .Build/bin/phpcs --runtime-set ignore_warnings_on_exit true --standard=PSR2 Classes/


jobs:
  fast_finish: true
  allow_failures:
    - env: TYPO3="dev-master"
  include:
    - stage: test
      php: 7.2
      env: TYPO3="dev-master"

    - stage: test
      php: 7.2
      env: TYPO3=^9.5

    - stage: test
      php: 7.1
      env: TYPO3=^8.7

    - stage: test
      php: 7.0
      env: TYPO3=^8.7

    - stage: ðŸš¢ to ter
      if: tag IS present AND env(TYPO3_ORG_USERNAME) IS present AND env(TYPO3_ORG_PASSWORD) IS present
      php: 7.0
      before_install: skip
      install: skip
      before_script: skip
      script:
        - >
          echo;
          echo "Preparing upload of release ${TRAVIS_TAG} to TER";
          echo;
          echo;
          composer global require helhum/ter-client;

        - >
          TAG_MESSAGE=`git tag -n10 -l $TRAVIS_TAG | sed 's/^[0-9.]*[ ]*//g'`;
          echo;
          echo "Cleanup before we upload";
          git reset --hard HEAD && git clean -fx;
          composer extension-cleanup-for-release;

          echo "Uploading release ${TRAVIS_TAG} to TER";
          echo;
          echo;
          $HOME/.composer/vendor/bin/ter-client upload $EXTENSION_KEY . -u "$TYPO3_ORG_USERNAME" -p "$TYPO3_ORG_PASSWORD" -m "$TAG_MESSAGE";
